# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miles/CS/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miles/CS/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/CS/compiler/CMakeFiles /home/miles/CS/compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/CS/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named null_first_test

# Build rule for target.
null_first_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 null_first_test
.PHONY : null_first_test

# fast build rule for target.
null_first_test/fast:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/build
.PHONY : null_first_test/fast

#=============================================================================
# Target rules for targets named lr0_test

# Build rule for target.
lr0_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lr0_test
.PHONY : lr0_test

# fast build rule for target.
lr0_test/fast:
	$(MAKE) -f CMakeFiles/lr0_test.dir/build.make CMakeFiles/lr0_test.dir/build
.PHONY : lr0_test/fast

#=============================================================================
# Target rules for targets named dfa_test

# Build rule for target.
dfa_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dfa_test
.PHONY : dfa_test

# fast build rule for target.
dfa_test/fast:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/build
.PHONY : dfa_test/fast

test/dfa_test.o: test/dfa_test.cpp.o

.PHONY : test/dfa_test.o

# target to build an object file
test/dfa_test.cpp.o:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.o
.PHONY : test/dfa_test.cpp.o

test/dfa_test.i: test/dfa_test.cpp.i

.PHONY : test/dfa_test.i

# target to preprocess a source file
test/dfa_test.cpp.i:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.i
.PHONY : test/dfa_test.cpp.i

test/dfa_test.s: test/dfa_test.cpp.s

.PHONY : test/dfa_test.s

# target to generate assembly for a file
test/dfa_test.cpp.s:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.s
.PHONY : test/dfa_test.cpp.s

test/lr0_test.o: test/lr0_test.cpp.o

.PHONY : test/lr0_test.o

# target to build an object file
test/lr0_test.cpp.o:
	$(MAKE) -f CMakeFiles/lr0_test.dir/build.make CMakeFiles/lr0_test.dir/test/lr0_test.cpp.o
.PHONY : test/lr0_test.cpp.o

test/lr0_test.i: test/lr0_test.cpp.i

.PHONY : test/lr0_test.i

# target to preprocess a source file
test/lr0_test.cpp.i:
	$(MAKE) -f CMakeFiles/lr0_test.dir/build.make CMakeFiles/lr0_test.dir/test/lr0_test.cpp.i
.PHONY : test/lr0_test.cpp.i

test/lr0_test.s: test/lr0_test.cpp.s

.PHONY : test/lr0_test.s

# target to generate assembly for a file
test/lr0_test.cpp.s:
	$(MAKE) -f CMakeFiles/lr0_test.dir/build.make CMakeFiles/lr0_test.dir/test/lr0_test.cpp.s
.PHONY : test/lr0_test.cpp.s

test/null_first_test.o: test/null_first_test.cpp.o

.PHONY : test/null_first_test.o

# target to build an object file
test/null_first_test.cpp.o:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.o
.PHONY : test/null_first_test.cpp.o

test/null_first_test.i: test/null_first_test.cpp.i

.PHONY : test/null_first_test.i

# target to preprocess a source file
test/null_first_test.cpp.i:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.i
.PHONY : test/null_first_test.cpp.i

test/null_first_test.s: test/null_first_test.cpp.s

.PHONY : test/null_first_test.s

# target to generate assembly for a file
test/null_first_test.cpp.s:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.s
.PHONY : test/null_first_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... null_first_test"
	@echo "... lr0_test"
	@echo "... edit_cache"
	@echo "... dfa_test"
	@echo "... test/dfa_test.o"
	@echo "... test/dfa_test.i"
	@echo "... test/dfa_test.s"
	@echo "... test/lr0_test.o"
	@echo "... test/lr0_test.i"
	@echo "... test/lr0_test.s"
	@echo "... test/null_first_test.o"
	@echo "... test/null_first_test.i"
	@echo "... test/null_first_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

