# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miles/CS/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miles/CS/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/CS/compiler/CMakeFiles /home/miles/CS/compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miles/CS/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named null_first_test

# Build rule for target.
null_first_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 null_first_test
.PHONY : null_first_test

# fast build rule for target.
null_first_test/fast:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/build
.PHONY : null_first_test/fast

#=============================================================================
# Target rules for targets named lr1_test

# Build rule for target.
lr1_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lr1_test
.PHONY : lr1_test

# fast build rule for target.
lr1_test/fast:
	$(MAKE) -f CMakeFiles/lr1_test.dir/build.make CMakeFiles/lr1_test.dir/build
.PHONY : lr1_test/fast

#=============================================================================
# Target rules for targets named dfa_test

# Build rule for target.
dfa_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dfa_test
.PHONY : dfa_test

# fast build rule for target.
dfa_test/fast:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/build
.PHONY : dfa_test/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named regex_test

# Build rule for target.
regex_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regex_test
.PHONY : regex_test

# fast build rule for target.
regex_test/fast:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/build
.PHONY : regex_test/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/regex.o: src/regex.cpp.o

.PHONY : src/regex.o

# target to build an object file
src/regex.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex.cpp.o
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex.cpp.o
.PHONY : src/regex.cpp.o

src/regex.i: src/regex.cpp.i

.PHONY : src/regex.i

# target to preprocess a source file
src/regex.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex.cpp.i
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex.cpp.i
.PHONY : src/regex.cpp.i

src/regex.s: src/regex.cpp.s

.PHONY : src/regex.s

# target to generate assembly for a file
src/regex.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex.cpp.s
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex.cpp.s
.PHONY : src/regex.cpp.s

src/regex_eval.o: src/regex_eval.cpp.o

.PHONY : src/regex_eval.o

# target to build an object file
src/regex_eval.cpp.o:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_eval.cpp.o
.PHONY : src/regex_eval.cpp.o

src/regex_eval.i: src/regex_eval.cpp.i

.PHONY : src/regex_eval.i

# target to preprocess a source file
src/regex_eval.cpp.i:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_eval.cpp.i
.PHONY : src/regex_eval.cpp.i

src/regex_eval.s: src/regex_eval.cpp.s

.PHONY : src/regex_eval.s

# target to generate assembly for a file
src/regex_eval.cpp.s:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_eval.cpp.s
.PHONY : src/regex_eval.cpp.s

src/regex_lexer.o: src/regex_lexer.cpp.o

.PHONY : src/regex_lexer.o

# target to build an object file
src/regex_lexer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex_lexer.cpp.o
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_lexer.cpp.o
.PHONY : src/regex_lexer.cpp.o

src/regex_lexer.i: src/regex_lexer.cpp.i

.PHONY : src/regex_lexer.i

# target to preprocess a source file
src/regex_lexer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex_lexer.cpp.i
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_lexer.cpp.i
.PHONY : src/regex_lexer.cpp.i

src/regex_lexer.s: src/regex_lexer.cpp.s

.PHONY : src/regex_lexer.s

# target to generate assembly for a file
src/regex_lexer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/regex_lexer.cpp.s
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/src/regex_lexer.cpp.s
.PHONY : src/regex_lexer.cpp.s

test/dfa_test.o: test/dfa_test.cpp.o

.PHONY : test/dfa_test.o

# target to build an object file
test/dfa_test.cpp.o:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.o
.PHONY : test/dfa_test.cpp.o

test/dfa_test.i: test/dfa_test.cpp.i

.PHONY : test/dfa_test.i

# target to preprocess a source file
test/dfa_test.cpp.i:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.i
.PHONY : test/dfa_test.cpp.i

test/dfa_test.s: test/dfa_test.cpp.s

.PHONY : test/dfa_test.s

# target to generate assembly for a file
test/dfa_test.cpp.s:
	$(MAKE) -f CMakeFiles/dfa_test.dir/build.make CMakeFiles/dfa_test.dir/test/dfa_test.cpp.s
.PHONY : test/dfa_test.cpp.s

test/lr1_test.o: test/lr1_test.cpp.o

.PHONY : test/lr1_test.o

# target to build an object file
test/lr1_test.cpp.o:
	$(MAKE) -f CMakeFiles/lr1_test.dir/build.make CMakeFiles/lr1_test.dir/test/lr1_test.cpp.o
.PHONY : test/lr1_test.cpp.o

test/lr1_test.i: test/lr1_test.cpp.i

.PHONY : test/lr1_test.i

# target to preprocess a source file
test/lr1_test.cpp.i:
	$(MAKE) -f CMakeFiles/lr1_test.dir/build.make CMakeFiles/lr1_test.dir/test/lr1_test.cpp.i
.PHONY : test/lr1_test.cpp.i

test/lr1_test.s: test/lr1_test.cpp.s

.PHONY : test/lr1_test.s

# target to generate assembly for a file
test/lr1_test.cpp.s:
	$(MAKE) -f CMakeFiles/lr1_test.dir/build.make CMakeFiles/lr1_test.dir/test/lr1_test.cpp.s
.PHONY : test/lr1_test.cpp.s

test/null_first_test.o: test/null_first_test.cpp.o

.PHONY : test/null_first_test.o

# target to build an object file
test/null_first_test.cpp.o:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.o
.PHONY : test/null_first_test.cpp.o

test/null_first_test.i: test/null_first_test.cpp.i

.PHONY : test/null_first_test.i

# target to preprocess a source file
test/null_first_test.cpp.i:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.i
.PHONY : test/null_first_test.cpp.i

test/null_first_test.s: test/null_first_test.cpp.s

.PHONY : test/null_first_test.s

# target to generate assembly for a file
test/null_first_test.cpp.s:
	$(MAKE) -f CMakeFiles/null_first_test.dir/build.make CMakeFiles/null_first_test.dir/test/null_first_test.cpp.s
.PHONY : test/null_first_test.cpp.s

test/regex_test.o: test/regex_test.cpp.o

.PHONY : test/regex_test.o

# target to build an object file
test/regex_test.cpp.o:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/test/regex_test.cpp.o
.PHONY : test/regex_test.cpp.o

test/regex_test.i: test/regex_test.cpp.i

.PHONY : test/regex_test.i

# target to preprocess a source file
test/regex_test.cpp.i:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/test/regex_test.cpp.i
.PHONY : test/regex_test.cpp.i

test/regex_test.s: test/regex_test.cpp.s

.PHONY : test/regex_test.s

# target to generate assembly for a file
test/regex_test.cpp.s:
	$(MAKE) -f CMakeFiles/regex_test.dir/build.make CMakeFiles/regex_test.dir/test/regex_test.cpp.s
.PHONY : test/regex_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... check"
	@echo "... null_first_test"
	@echo "... lr1_test"
	@echo "... dfa_test"
	@echo "... main"
	@echo "... regex_test"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/regex.o"
	@echo "... src/regex.i"
	@echo "... src/regex.s"
	@echo "... src/regex_eval.o"
	@echo "... src/regex_eval.i"
	@echo "... src/regex_eval.s"
	@echo "... src/regex_lexer.o"
	@echo "... src/regex_lexer.i"
	@echo "... src/regex_lexer.s"
	@echo "... test/dfa_test.o"
	@echo "... test/dfa_test.i"
	@echo "... test/dfa_test.s"
	@echo "... test/lr1_test.o"
	@echo "... test/lr1_test.i"
	@echo "... test/lr1_test.s"
	@echo "... test/null_first_test.o"
	@echo "... test/null_first_test.i"
	@echo "... test/null_first_test.s"
	@echo "... test/regex_test.o"
	@echo "... test/regex_test.i"
	@echo "... test/regex_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

